=== blacksmoke26/csharp-image-uploader/ImageShare/Resources/Schemas/ImageService.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "ImagePix - Image service schema",
  "$comment": "Image service schema to generate ui and service related functionality at runtime",
  "type": "object",
  "properties": {
    "ServiceName": {
      "type": "string",
      "minLength": 5,
      "maxLength": 25,
      "pattern": "^([A-Z]+[a-z0-9]+)+$"
    },
    "Title": {
      "type": "string",
      "minLength": 5,
      "maxLength": 60
    },
    "Menu": {
      "type": "object",
      "properties": {
        "Text": {
          "type": "string",
          "minLength": 5,
          "maxLength": 30
        },
        "Icon": {
          "$comment": "Icon unicode symbol from phosphoricons.com",
          "type": "string",
          "pattern": "^\\\\u[A-Z0-9]{4}$"
        }
      },
      "required": [
        "Text",
        "Icon"
      ]
    },
    "Logo": {
      "$comment": "The base64 encoded image string",
      "type": "string",
      "pattern": "^data:(.+);base64,[^=]+=$"
    },
    "DocsUrl": {
      "type": "string",
      "format": "uri",
      "pattern": "^https?://"
    },
    "Description": {
      "type": "string",
      "minLength": 10,
      "maxLength": 150
    },
    "ExpirationRange": {
      "type": "array",
      "minItems": 0,
      "items": {
        "type": "object",
        "properties": {
          "Label": {
            "type": "string"
          },
          "Value": {
            "type": "string",
            "pattern": "^(None|((TM|TH|ED|EW|EM)[0-9]+))$"
          }
        },
        "required": [
          "Label",
          "Value"
        ]
      }
    },
    "VariablePrefix": {
      "type": "string",
      "pattern": "^[A-Z](_[A-Z]|[A-Z])+$",
      "minLength": 3,
      "maxLength": 20
    },
    "Variables": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "Key": {
            "type": "string",
            "pattern": "^[A-Z](_[A-Z]|[A-Z])+$"
          },
          "Type": {
            "type": "string",
            "enum": ["String", "Bool", "Double", "Int"]
          },
          "TargetParam": {
            "type": "string",
            "enum": ["Custom", "Endpoint", "ApiKey", "FileType", "FileSizeMin", "FileSizeMax"]
          },
          "InputField": {
            "type": "object",
            "properties": {
              "Label": {
                "type": "string",
                "minLength": 3,
                "maxLength": 60
              },
              "Type": {
                "type": "string",
                "enum": ["Text", "Url", "Toggle", "Double", "Integer", "List"]
              },
              "ExactLength": {
                "type": "integer",
                "minimum": 1,
                "maximum": 300
              },
              "MinLength": {
                "type": "integer"
              },
              "MaxLength": {
                "type": "integer"
              },
              "Minimum": {
                "type": "integer"
              },
              "Maximum": {
                "type": "integer"
              },
              "IsRequired": {
                "type": "boolean",
                "default": false
              },
              "Pattern": {
                "type": "string"
              },
              "Items": {
                "type": "array",
                "minItems": 0,
                "items": {
                  "type": "object",
                  "properties": {
                    "Label": {
                      "type": "string",
                      "minLength": 3,
                      "maxLength": 30
                    },
                    "Value": {
                      "type": "string",
                      "minLength": 1,
                      "maxLength": 40
                    }
                  },
                  "required": [
                    "Label",
                    "Value"
                  ]
                }
              }
            },
            "required": ["Label", "Type"]
          }
        },
        "required": [
          "Key",
          "Type",
          "TargetParam",
          "InputField"
        ],
        "additionalProperties": false
      }
    },
    "RequestProps": {
      "type": "object",
      "properties": {
        "Endpoint": {
          "type": "string",
          "format": "uri",
          "pattern": "^https?://"
        },
        "FileInfo": {
          "type": "object",
          "properties": {
            "AllowedTypes": {
              "type": "array",
              "items": {
                "type": "string",
                "pattern": "^[a-z][a-z0-9]+$"
              }
            },
            "Size": {
              "type": "object",
              "properties": {
                "Minimum": {
                  "type": "integer"
                },
                "Maximum": {
                  "type": "integer"
                }
              },
              "required": [
                "Minimum",
                "Maximum"
              ]
            }
          },
          "required": [
            "AllowedTypes",
            "Size"
          ]
        },
        "KeyConfig": {
          "type": "object",
          "properties": {
            "Image": {
              "type": "object",
              "properties": {
                "Key": {
                  "type": "string",
                  "minLength": 2,
                  "maxLength": 50,
                  "pattern": "^[a-z]+((_|[A-Z])[a-z0-9]+)*$"
                },
                "IsRequired": {
                  "type": "boolean"
                },
                "UseInRequest": {
                  "type": "boolean"
                }
              },
              "required": [
                "Key",
                "IsRequired",
                "UseInRequest"
              ]
            },
            "Api": {
              "type": "object",
              "properties": {
                "Key": {
                  "type": "string"
                },
                "IsRequired": {
                  "type": "boolean"
                },
                "UseInRequest": {
                  "type": "boolean"
                }
              },
              "required": [
                "Key",
                "IsRequired",
                "UseInRequest"
              ]
            },
            "Caption": {
              "type": "object",
              "properties": {
                "Key": {
                  "type": "string"
                },
                "IsRequired": {
                  "type": "boolean"
                },
                "UseInRequest": {
                  "type": "boolean"
                }
              },
              "required": [
                "Key",
                "IsRequired",
                "UseInRequest"
              ]
            },
            "Expiration": {
              "type": "object",
              "properties": {
                "Key": {
                  "type": "string",
                  "pattern": "^[a-z](_[a-z]|[a-z])+$",
                  "minLength": 3,
                  "maxLength": 15
                },
                "IsRequired": {
                  "type": "boolean",
                  "default": true
                },
                "UseInRequest": {
                  "type": "boolean",
                  "default": true
                }
              },
              "required": [
                "Key",
                "IsRequired",
                "UseInRequest"
              ]
            }
          },
          "required": [
            "Image",
            "Api",
            "Caption",
            "Expiration"
          ]
        }
      },
      "required": [
        "Endpoint",
        "FileInfo",
        "KeyConfig"
      ],
      "additionalProperties": false
    }
  },
  "required": [
    "ServiceName",
    "Title",
    "Menu",
    "Logo",
    "DocsUrl",
    "Description",
    "ExpirationRange",
    "VariablePrefix",
    "Variables",
    "RequestProps"
  ],
  "additionalProperties": false
}

=== blacksmoke26/csharp-image-uploader/ImageShare/Services/Available/ImgBb.service.json
{
	"ServiceName": "ImgBb",
	"Title": "ImgBB",
	"Menu": {
		"Text": "ImgBB",
		"Icon": "\\uE5D4"
	},
	"Logo": "data:image/jpeg;base64,iVBORw0KGgoAAAANSUhEUgAAAFUAAAAgCAMAAABUxMQaAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAk1BMVEVHcEwip+Aip98ip98ip98iotgiotkiqN8io9whpdsdk8QiqOAiqOAAbZMiqN8ipt0ipt8ip+Aip94ip98ipuAdntMhpt4ip98ipdwjp90iqN8iqN8ioNoiqOAjqN8ip+AiqOAiqOAip+Ahpd4hpt4ip+Ahpt4ip98ip98iqOAip+AeoNAip+AYisUhpd4jqOD////CaEQTAAAAL3RSTlMAtbySXhUczSklB/vwAdU5cIRPVHwQWWgvQKOMIeP+9dGq3EVJ6zuAnMOWCsgDNdQDw2IAAAABYktHRDCu3C3kAAAAB3RJTUUH6QEQEScOsH/I4AAAAp5JREFUSMe1VWuXojAMjaMgDxEE8W1RFB+L2v//77ZN0sLguGc8x80H6W2T2zTNrQD/zXpS2debQX0dJAcvsYNYuu+xDjHIe4ldYvXfIg1CHTOKXmHeZhy9xRrL72XrYgB/rEi9t0ghQZbJSwxxmk2nWY4jbf4sSWaOqkw2T1vFXgySmYsOS4VWyLKezza02sWwxQnHjEShf4sU/YoJF2a5k9b2CpcGiD56dDG1QGlHbCF/EySdi9ZS8t01gWcMqd0/lT/YTvsccA9Bp5IxwLHlsYVnDBO7AY2kOQxxVLr3KqzGKcLihAHAGdcu8ZV7sovhCydOZiR6EXLIP9HIlOaCE3Pw8TsElqMKmunP4RkDcoQ1ALGJTY3HLRxA1qtKFSfKCAa0nQ0KqE2zZ+zb6plMTvjtseb6AGtTI6t1mzT6Hp9wa38zooY+Q2Y4qNB+S+szE5TR7XVx660xo72kDSnFDedctbVug7SPqJ8w3HBiAfd6zJnQ3eeU2dZ0zbXRelDvTPYlVe/WwXdsliLi3lCZGFVQZnsIpGloo3UqhKwiWOrvFKjjGsx1vkLOHf7FWljBQpLL3LDeiS1dSON61zmGLteowXzhw+OVXSdWFXhwsRpgf0lRHane0umxa3lY8R0tOhjMxsZSVkUMB/mjbacq7zbO7btvMQQFo4qeE5cUpRraMQ/K7tZmVW7jfGzh6KFV38VG/NuloCtvVHnhFf9RtGll6fJro8cLaF6fBkN0VjHVOj/wnTSqCCZKh+FeFT9uZVusa/3c6psTtyTgN7qLAWrPffGfFW28nEYb85AJh9ccb1O3fbv4F9YUcvxm5L9MCXE3saX5lKnzL2/ceZ8zJTx6yrf3D7IaOX00VeCOFcknSQG8VRlW+8cvvf8Cc/3adz65S1AAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjUtMDEtMTZUMTc6Mzg6NDMrMDA6MDCbK2ZxAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI1LTAxLTE2VDE3OjM4OjQzKzAwOjAw6nbezQAAAABJRU5ErkJggg==",
	"DocsUrl": "https://api.imgbb.com/",
	"Description": "Free image hosting and sharing service, upload pictures, photo host.",
	"ExpirationRange": [
		{
			"Value": "None",
			"Label": "Don't auto delete"
		},
		{
			"Value": "TM5",
			"Label": "After 5 minutes"
		},
		{
			"Value": "TM15",
			"Label": "After 15 minutes"
		},
		{
			"Value": "TM30",
			"Label": "After 30 minutes"
		},
		{
			"Value": "TH1",
			"Label": "After 1 hour"
		},
		{
			"Value": "TH3",
			"Label": "After 3 hours"
		},
		{
			"Value": "TH6",
			"Label": "After 6 hours"
		},
		{
			"Value": "TH12",
			"Label": "After 12 hours"
		},
		{
			"Value": "ED1",
			"Label": "After 1 day"
		},
		{
			"Value": "ED2",
			"Label": "After 2 days"
		},
		{
			"Value": "ED3",
			"Label": "After 3 days"
		},
		{
			"Value": "ED4",
			"Label": "After 4 days"
		},
		{
			"Value": "ED5",
			"Label": "After 5 days"
		},
		{
			"Value": "ED6",
			"Label": "After 6 days"
		},
		{
			"Value": "EW1",
			"Label": "After 1 week"
		},
		{
			"Value": "EW2",
			"Label": "After 2 weeks"
		},
		{
			"Value": "EW3",
			"Label": "After 3 weeks"
		},
		{
			"Value": "EM1",
			"Label": "After 1 month"
		},
		{
			"Value": "EM2",
			"Label": "After 2 months"
		},
		{
			"Value": "EM3",
			"Label": "After 3 months"
		},
		{
			"Value": "EM4",
			"Label": "After 4 months"
		},
		{
			"Value": "EM5",
			"Label": "After 5 months"
		},
		{
			"Value": "EM6",
			"Label": "After 6 months"
		}
	],
	"VariablePrefix": "IMGBB",
	"Variables": [
		{
			"Key": "ENDPOINT",
			"Type": "String",
			"TargetParam": "Endpoint",
			"InputField": {
				"Label": "Endpoint URL",
				"Type": "Url",
				"IsRequired": true
			}
		},
		{
			"Key": "APIKEY",
			"Type": "String",
			"TargetParam": "ApiKey",
			"InputField": {
				"Label": "Api Key",
				"Type": "Text",
				"ExactLength": 32,
				"IsRequired": true
			}
		}
	],
	"RequestProps": {
		"Endpoint": "https://api.imgbb.com/1/upload",
		"FileInfo": {
			"AllowedTypes": ["jpg", "jpeg", "jfif", "png", "gif", "bmp", "webp"],
			"Size": {
				"Minimum": 1,
				"Maximum": 33554432
			}
		},
		"KeyConfig": {
			"Image": {
				"Key": "image",
				"IsRequired": true,
				"UseInRequest": true
			},
			"Api": {
				"Key": "key",
				"IsRequired": true,
				"UseInRequest": true
			},
			"Caption": {
				"Key": "name",
				"IsRequired": false,
				"UseInRequest": true
			},
			"Expiration": {
				"Key": "expiration",
				"IsRequired": false,
				"UseInRequest": true
			}
		}
	}
}
